name: Deploy Backend to Render

on:
  push:
    branches:
      - main
    paths:
      - 'server.mjs'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Backend Dependencies
        run: npm ci

      - name: Run Backend Tests
        run: npm test

      - name: Trigger Render Backend Deploy
        env:
          RENDER_BACKEND_DEPLOY_HOOK_URL: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$RENDER_BACKEND_DEPLOY_HOOK_URL" ]; then
            echo "RENDER_BACKEND_DEPLOY_HOOK_URL secret not set. Skipping Render deploy trigger."
          else
            curl -X POST $RENDER_BACKEND_DEPLOY_HOOK_URL
            echo "Successfully triggered Render deploy for backend."
          fi