name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # gh-pages branch 

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.4.0 
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build the app
      run: npm run build
    - name: Run component tests
      run: npm run test

    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages

    - name: Configure Git user
      run: |
        cd gh-pages
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "GitHub Actions Bot"

    - name: Copy built artifacts to gh-pages
      run: |
        cd gh-pages
        rm -rf *
        cp -r ../build/* .

    - name: Commit and push changes to gh-pages
      run: |
        cd gh-pages
        git add .
        git commit -m "Deploy website"
        git push origin gh-pages